# Generated by Django 5.0.2 on 2024-06-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="region",
            field=models.CharField(
                choices=[("Asia", "Asia"), ("Europe", "Europe"), ("China", "China")],
                default="Asia",
                max_length=10,
            ),
        ),
    ]
